package org.example.domain;

public enum PaymentState {
    NEW,
    PREAUTH_PENDING, PREAUTH_AUTHORIZED,
    TOPUP_PENDING, TOPUP_AUTHORIZED,
    COMPLETION_PENDING, COMPLETED,
    SALE_PENDING, SALE_COMPLETED,
    PREAUTH_REVERSED, COMPLETION_REVERSED,
    PREAUTH_REVERSAL_PENDING,  COMPLETION_REVERSAL_PENDING,
    FAILED
}
